name: Kustomize Job
description: Runs your build step as a kustomized kubernetes job
author: https://github.com/pr8kerl
requirements:
  - kubectl
  - kustomize
configuration:
  properties:
    name:
      type: string
    overlay:
      type: array
    debug:
      type: string
    secret-name:
      type: string
    secret-key:
      type: string
    timeout:
      type: integer
    init-image:
      type: string
    init-image-tag:
      type: string
  required:
    - name
    - overlay
  additionalProperties: false
