#!/bin/bash

set -euo pipefail

debug_mode='off'
if [[ "${BUILDKITE_PLUGIN_K8S_JOB_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  debug_mode='on'
fi

echo
echo pwd: $(pwd)
echo ls: $(ls)
echo env: $(env)
